package net.chuangdie.lhb.bean;

import org.springframework.jdbc.core.JdbcTemplate;

public class Transaction implements Com
{
	private Integer id;
	private Double in_cash;
	private Double out_cash;
	private Integer create_date;

	public void createTable()
	{
		String sql = "create table p_transaction("
				+ "id bigint not null generated by default as identity,"
				+ "in_cash double, out_cash double, create_date int)";
		jdbcTemplate.execute(sql);
	}

	public int insert(Transaction transaction)
	{
		String sql = "insert into pa_transaction (in_cash, out_cash, create_date)"
				+ "values(?, ?, ?)";
		Object[] params = new Object[]
		{ transaction.getIn_cash(), transaction.getOut_cash(), transaction.getCreate_date() };
		return jdbcTemplate.update(sql, params);
	}

	private JdbcTemplate jdbcTemplate;

	public void setJdbcTemplate(JdbcTemplate jdbcTemplate)
	{
		this.jdbcTemplate = jdbcTemplate;
	}

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Double getIn_cash()
	{
		return in_cash;
	}

	public void setIn_cash(Double in_cash)
	{
		this.in_cash = in_cash;
	}

	public Double getOut_cash()
	{
		return out_cash;
	}

	public void setOut_cash(Double out_cash)
	{
		this.out_cash = out_cash;
	}

	public Integer getCreate_date()
	{
		return create_date;
	}

	public void setCreate_date(Integer create_date)
	{
		this.create_date = create_date;
	}

}
